set_property PACKAGE_PIN K17 [get_ports clk]
set_property PACKAGE_PIN M19 [get_ports rst_n]
set_property PACKAGE_PIN N20 [get_ports tx_out]
set_property PACKAGE_PIN P20 [get_ports rx_in]
set_property PACKAGE_PIN T12 [get_ports count[0]]
set_property PACKAGE_PIN U12 [get_ports count[1]]
set_property PACKAGE_PIN V12 [get_ports count[2]]
set_property PACKAGE_PIN W13 [get_ports count[3]]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports tx_out]
set_property IOSTANDARD LVCMOS33 [get_ports rx_in]
set_property IOSTANDARD LVCMOS33 [get_ports count[0]]
set_property IOSTANDARD LVCMOS33 [get_ports count[1]]
set_property IOSTANDARD LVCMOS33 [get_ports count[2]]
set_property IOSTANDARD LVCMOS33 [get_ports count[3]]